Compile before submitting

diff --git a/submitlab b/submitlab
--- a/submitlab
+++ b/submitlab
@@ -50,6 +50,15 @@ then
   git config user.email "$username@gototicmail.com"
 fi
 
+# Compile project
+if [ ! -f "compile.sh" ]
+then
+  printf "\n\n${red}ERROR: no encuentro el script para compilar, 'compile.sh'.\n\n${end}"
+  [[ $0 = "$BASH_SOURCE" ]] && exit 1 || return 1
+fi
+echo -e "\n\n=====================================\nCompiling the program...\n=====================================\n"
+source ./compile.sh
+
 # Check if repo is up-to-date
 if [ -n "$(git status --porcelain)" ]
 then
